package com.lkh.sboot.mapper;

import com.lkh.sboot.entity.Dept;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int deleteByPrimaryKey(String dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    Dept selectByPrimaryKey(String dept_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dept
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKey(Dept record);

    public List<Map<String,Object>> getListByParentDeptId(@Param("parent_dept_id") String parent_dept_id);

}