package com.lkh.sboot.mapper;

import com.lkh.sboot.entity.Menu;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int deleteByPrimaryKey(String menu_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    Menu selectByPrimaryKey(String menu_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_menu
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKey(Menu record);
    public List<Map<String,Object>> getListByParentMenuId(@Param("parent_menu_id") String parent_menu_id);
    public List<Map<String,Object>> getListByParentMenuIdAndRole(@Param("parent_menu_id") String parent_menu_id,@Param("role_id") String role_id);

}