package com.lkh.sboot.mapper;

import com.lkh.sboot.entity.Role;

import java.util.List;
import java.util.Map;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int deleteByPrimaryKey(String role_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    Role selectByPrimaryKey(String role_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKey(Role record);


    public List<Map<String,Object>> getList();

}