package com.lkh.sboot.mapper;

import com.lkh.sboot.entity.RolePermission;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insertSelective(RolePermission record);
    int delRolePermissionByRoleId(@Param("role_id") String role_id);
}