package com.lkh.sboot.mapper;

import com.lkh.sboot.entity.User;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int deleteByPrimaryKey(String user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    User selectByPrimaryKey(String user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    int updateByPrimaryKey(User record);

    public List<Map<String,Object>> getList(@Param("dept_id") String dept_id,
                                            @Param("user_name") String user_name,
                                            @Param("user_realname") String user_realname,
                                            @Param("user_phone") String user_phone,
                                            @Param("user_sex") String user_sex
    );



    public List<User> findByUsername(@Param("user_name") String user_name);
}