package com.lkh.sboot.entity;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String menu_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String menu_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.parent_menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String parent_menu_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_order
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private Integer menu_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menu.menu_url
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String menu_url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_id
     *
     * @return the value of sys_menu.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getMenu_id() {
        return menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_id
     *
     * @param menu_id the value for sys_menu.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setMenu_id(String menu_id) {
        this.menu_id = menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_name
     *
     * @return the value of sys_menu.menu_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getMenu_name() {
        return menu_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_name
     *
     * @param menu_name the value for sys_menu.menu_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setMenu_name(String menu_name) {
        this.menu_name = menu_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.parent_menu_id
     *
     * @return the value of sys_menu.parent_menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getParent_menu_id() {
        return parent_menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.parent_menu_id
     *
     * @param parent_menu_id the value for sys_menu.parent_menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setParent_menu_id(String parent_menu_id) {
        this.parent_menu_id = parent_menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_order
     *
     * @return the value of sys_menu.menu_order
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public Integer getMenu_order() {
        return menu_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_order
     *
     * @param menu_order the value for sys_menu.menu_order
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setMenu_order(Integer menu_order) {
        this.menu_order = menu_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menu.menu_url
     *
     * @return the value of sys_menu.menu_url
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getMenu_url() {
        return menu_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menu.menu_url
     *
     * @param menu_url the value for sys_menu.menu_url
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setMenu_url(String menu_url) {
        this.menu_url = menu_url;
    }
}