package com.lkh.sboot.entity;

public class Permission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.perm_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String perm_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.perm_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String perm_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.perm_flag
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String perm_flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String menu_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.perm_id
     *
     * @return the value of sys_permission.perm_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getPerm_id() {
        return perm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.perm_id
     *
     * @param perm_id the value for sys_permission.perm_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setPerm_id(String perm_id) {
        this.perm_id = perm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.perm_name
     *
     * @return the value of sys_permission.perm_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getPerm_name() {
        return perm_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.perm_name
     *
     * @param perm_name the value for sys_permission.perm_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setPerm_name(String perm_name) {
        this.perm_name = perm_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.perm_flag
     *
     * @return the value of sys_permission.perm_flag
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getPerm_flag() {
        return perm_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.perm_flag
     *
     * @param perm_flag the value for sys_permission.perm_flag
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setPerm_flag(String perm_flag) {
        this.perm_flag = perm_flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.menu_id
     *
     * @return the value of sys_permission.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getMenu_id() {
        return menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.menu_id
     *
     * @param menu_id the value for sys_permission.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setMenu_id(String menu_id) {
        this.menu_id = menu_id;
    }
}