package com.lkh.sboot.entity;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String role_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_note
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String role_note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param role_id the value for sys_role.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getRole_name() {
        return role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param role_name the value for sys_role.role_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setRole_name(String role_name) {
        this.role_name = role_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_note
     *
     * @return the value of sys_role.role_note
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getRole_note() {
        return role_note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_note
     *
     * @param role_note the value for sys_role.role_note
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setRole_note(String role_note) {
        this.role_note = role_note;
    }
}