package com.lkh.sboot.entity;

public class RoleMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String role_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_menu.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String menu_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.role_id
     *
     * @return the value of sys_role_menu.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.role_id
     *
     * @param role_id the value for sys_role_menu.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_menu.menu_id
     *
     * @return the value of sys_role_menu.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getMenu_id() {
        return menu_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_menu.menu_id
     *
     * @param menu_id the value for sys_role_menu.menu_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setMenu_id(String menu_id) {
        this.menu_id = menu_id;
    }
}