package com.lkh.sboot.entity;

public class RolePermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.perm_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String perm_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String role_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.perm_id
     *
     * @return the value of sys_role_permission.perm_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getPerm_id() {
        return perm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.perm_id
     *
     * @param perm_id the value for sys_role_permission.perm_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setPerm_id(String perm_id) {
        this.perm_id = perm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.role_id
     *
     * @return the value of sys_role_permission.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.role_id
     *
     * @param role_id the value for sys_role_permission.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }
}