package com.lkh.sboot.entity;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String role_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.user_id
     *
     * @return the value of sys_user_role.user_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.user_id
     *
     * @param user_id the value for sys_user_role.user_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.role_id
     *
     * @return the value of sys_user_role.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getRole_id() {
        return role_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.role_id
     *
     * @param role_id the value for sys_user_role.role_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }
}