package com.lkh.sboot.entity;

import java.util.Date;

public class User {

    private String role_id;

    public String getRole_id() {
        return role_id;
    }

    public void setRole_id(String role_id) {
        this.role_id = role_id;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_pwd
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_realname
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_sex
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_phone
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_addr
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String user_addr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.dept_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String dept_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.lastest_time
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private Date lastest_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.lastest_ip
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    private String lastest_ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_id
     *
     * @return the value of sys_user.user_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_id
     *
     * @param user_id the value for sys_user.user_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param user_name the value for sys_user.user_name
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_pwd
     *
     * @return the value of sys_user.user_pwd
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_pwd() {
        return user_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_pwd
     *
     * @param user_pwd the value for sys_user.user_pwd
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_pwd(String user_pwd) {
        this.user_pwd = user_pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_realname
     *
     * @return the value of sys_user.user_realname
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_realname() {
        return user_realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_realname
     *
     * @param user_realname the value for sys_user.user_realname
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_realname(String user_realname) {
        this.user_realname = user_realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_sex
     *
     * @return the value of sys_user.user_sex
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_sex() {
        return user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_sex
     *
     * @param user_sex the value for sys_user.user_sex
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_sex(String user_sex) {
        this.user_sex = user_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_phone
     *
     * @return the value of sys_user.user_phone
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_phone() {
        return user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_phone
     *
     * @param user_phone the value for sys_user.user_phone
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_phone(String user_phone) {
        this.user_phone = user_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_addr
     *
     * @return the value of sys_user.user_addr
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getUser_addr() {
        return user_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_addr
     *
     * @param user_addr the value for sys_user.user_addr
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setUser_addr(String user_addr) {
        this.user_addr = user_addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.dept_id
     *
     * @return the value of sys_user.dept_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getDept_id() {
        return dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.dept_id
     *
     * @param dept_id the value for sys_user.dept_id
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setDept_id(String dept_id) {
        this.dept_id = dept_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.lastest_time
     *
     * @return the value of sys_user.lastest_time
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public Date getLastest_time() {
        return lastest_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.lastest_time
     *
     * @param lastest_time the value for sys_user.lastest_time
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setLastest_time(Date lastest_time) {
        this.lastest_time = lastest_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.lastest_ip
     *
     * @return the value of sys_user.lastest_ip
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public String getLastest_ip() {
        return lastest_ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.lastest_ip
     *
     * @param lastest_ip the value for sys_user.lastest_ip
     *
     * @mbg.generated Wed Jun 06 10:04:02 CST 2018
     */
    public void setLastest_ip(String lastest_ip) {
        this.lastest_ip = lastest_ip;
    }
}